name: CI.2

on: 
  push:
    paths:
      - '2.c'
      - 'fuzzer_test.c'
      - '.github/workflows/*'

jobs:
  fuzzy_test:
    name: Fuzzy testing
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install clang
      run: |
        sudo apt-get update
        sudo apt install clang
    - name: Run tests
      run: |
        clang fuzzer_test.c -fsanitize=address,fuzzer -o fuzzer
        ./fuzzer -max_total_time=5 -runs=250000 2> error
        cat error
  
  unit_test:
    name: Unit testing
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        g++ tests/tests.c -o tests
        ./tests
